org: "deisci"
pull_policy: "Always"
docker_tag: canary
# limits_cpu: "100m"
# limits_memory: "50Mi"

# Time in minutes after which the token should be refreshed.
# Leave it empty to use the default provider time.
token_refresh_time: ""
off_cluster_registry:
  hostname: ""
  organization: ""
  username: ""
  password: ""
ecr:
  # Your AWS access key. Leave it empty if you want to use IAM credentials.
  accesskey: ""
  # Your AWS secret key. Leave it empty if you want to use IAM credentials.
  secretkey: ""
  # Any S3 region
  region: "us-west-2"
  registryid: ""
  hostname: ""
gcr:
  key_json: 'Paste JSON data here.'
  hostname: ""

global:
  # Set the location of Workflow's Registry
  #
  # Valid values are:
  # - on-cluster: Run registry within the Kubernetes cluster
  # - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,quay.io,self-hosted)
  # - ecr: Use Amazon's ECR
  # - gcr: Use Google's GCR
  registry_location: "on-cluster"
  # Prefix for the imagepull secret created when using private registry
  secret_prefix: "private-registry"
